//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStudentGradeBook_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EStudentGradeBookDBContext : DbContext
    {
        public EStudentGradeBookDBContext()
            : base("name=EStudentGradeBookDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grouplesson> grouplessons { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<mark> marks { get; set; }
        public virtual DbSet<student> students { get; set; }
    }
}
