//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStudentGradeBook_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int mark_id { get; set; }
        public int mark_student_id { get; set; }
        public int mark_lesson_id { get; set; }
        public int mark_value { get; set; }
        public Nullable<System.DateTime> mark_date { get; set; }
    
        public virtual Lesson lesson { get; set; }
        public virtual Student student { get; set; }
    }
}
